version: "3.8"

services:
  redis-1:
    container_name: "redis-alias1"
    image: "seffeng/redis"
    ports:
      - "6379:6379"
    networks:
      network-01:
        aliases:
          - redis-net1
    volumes:
      - "/srv/websrv/data/redis:/opt/websrv/data/redis"
      - "/srv/websrv/tmp:/opt/websrv/tmp"

networks:
  network-01:
    driver: bridge
    name: network-01